name: linux

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-linux:
    name: Test (Linux)
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip validation]')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Kernelle Dependencies
        uses: ./.github/actions/setup-kernelle

      - name: Test with Coverage (PR)
        if: github.event_name == 'pull_request'
        uses: ./.github/actions/test
        with:
          report-coverage: 'true'
          post-pr-comment: 'true'

      - name: Test with Coverage (Push)
        if: github.event_name == 'push'
        uses: ./.github/actions/test
        with:
          report-coverage: 'true'
          update-badge: 'true'
